### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by marzad** [marzad/training-journal#12]
## Tasks
(for developers team)
- [x] Create feature branch
- [x] create a JSON file containing an Array filled with informations on all the elements
- [ ] using React Modals to create popup windows
- [ ] fill the popup windows with the informations from the JSON file
